# Generated by Django 3.0.8 on 2020-09-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembrete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
